// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=../repo/storage-mock.go -package=repo
//

// Package repo is a generated GoMock package.
package repo

import (
	os "os"
	reflect "reflect"

	entity "github.com/Netcracker/qubership-backup-daemon-go/backup-daemon/app/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageRepository is a mock of StorageRepository interface.
type MockStorageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStorageRepositoryMockRecorder
	isgomock struct{}
}

// MockStorageRepositoryMockRecorder is the mock recorder for MockStorageRepository.
type MockStorageRepositoryMockRecorder struct {
	mock *MockStorageRepository
}

// NewMockStorageRepository creates a new mock instance.
func NewMockStorageRepository(ctrl *gomock.Controller) *MockStorageRepository {
	mock := &MockStorageRepository{ctrl: ctrl}
	mock.recorder = &MockStorageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageRepository) EXPECT() *MockStorageRepositoryMockRecorder {
	return m.recorder
}

// CloseVault mocks base method.
func (m *MockStorageRepository) CloseVault(vault entity.Vault) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseVault", vault)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseVault indicates an expected call of CloseVault.
func (mr *MockStorageRepositoryMockRecorder) CloseVault(vault any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseVault", reflect.TypeOf((*MockStorageRepository)(nil).CloseVault), vault)
}

// Evict mocks base method.
func (m *MockStorageRepository) Evict(vaultName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evict", vaultName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Evict indicates an expected call of Evict.
func (mr *MockStorageRepositoryMockRecorder) Evict(vaultName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evict", reflect.TypeOf((*MockStorageRepository)(nil).Evict), vaultName)
}

// FindByTS mocks base method.
func (m *MockStorageRepository) FindByTS(timestamp, typeOfBackup, storagePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTS", timestamp, typeOfBackup, storagePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTS indicates an expected call of FindByTS.
func (mr *MockStorageRepositoryMockRecorder) FindByTS(timestamp, typeOfBackup, storagePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTS", reflect.TypeOf((*MockStorageRepository)(nil).FindByTS), timestamp, typeOfBackup, storagePath)
}

// GetName mocks base method.
func (m *MockStorageRepository) GetName(folder string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName", folder)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockStorageRepositoryMockRecorder) GetName(folder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockStorageRepository)(nil).GetName), folder)
}

// GetNonEvictableVaults mocks base method.
func (m *MockStorageRepository) GetNonEvictableVaults(typeOfBackup string) (map[int64]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonEvictableVaults", typeOfBackup)
	ret0, _ := ret[0].(map[int64]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNonEvictableVaults indicates an expected call of GetNonEvictableVaults.
func (mr *MockStorageRepositoryMockRecorder) GetNonEvictableVaults(typeOfBackup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonEvictableVaults", reflect.TypeOf((*MockStorageRepository)(nil).GetNonEvictableVaults), typeOfBackup)
}

// GetRoot mocks base method.
func (m *MockStorageRepository) GetRoot() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoot")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRoot indicates an expected call of GetRoot.
func (mr *MockStorageRepositoryMockRecorder) GetRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoot", reflect.TypeOf((*MockStorageRepository)(nil).GetRoot))
}

// GetVault mocks base method.
func (m *MockStorageRepository) GetVault(vaultName string, external bool, vaultPath, blobPath string, skipFSCheck bool) entity.Vault {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVault", vaultName, external, vaultPath, blobPath, skipFSCheck)
	ret0, _ := ret[0].(entity.Vault)
	return ret0
}

// GetVault indicates an expected call of GetVault.
func (mr *MockStorageRepositoryMockRecorder) GetVault(vaultName, external, vaultPath, blobPath, skipFSCheck any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVault", reflect.TypeOf((*MockStorageRepository)(nil).GetVault), vaultName, external, vaultPath, blobPath, skipFSCheck)
}

// List mocks base method.
func (m *MockStorageRepository) List(typeOfBackup, storagePath string) ([]entity.Vault, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", typeOfBackup, storagePath)
	ret0, _ := ret[0].([]entity.Vault)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStorageRepositoryMockRecorder) List(typeOfBackup, storagePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStorageRepository)(nil).List), typeOfBackup, storagePath)
}

// ListVaultNames mocks base method.
func (m *MockStorageRepository) ListVaultNames(convertToTs bool, typeOfBackup, storagePath string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVaultNames", convertToTs, typeOfBackup, storagePath)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVaultNames indicates an expected call of ListVaultNames.
func (mr *MockStorageRepositoryMockRecorder) ListVaultNames(convertToTs, typeOfBackup, storagePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVaultNames", reflect.TypeOf((*MockStorageRepository)(nil).ListVaultNames), convertToTs, typeOfBackup, storagePath)
}

// OpenVault mocks base method.
func (m *MockStorageRepository) OpenVault(vaultName string, allowEviction, isGranular, isSharded, isExternal bool, vaultPath, backupPrefix, blobPath string) (entity.Vault, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenVault", vaultName, allowEviction, isGranular, isSharded, isExternal, vaultPath, backupPrefix, blobPath)
	ret0, _ := ret[0].(entity.Vault)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenVault indicates an expected call of OpenVault.
func (mr *MockStorageRepositoryMockRecorder) OpenVault(vaultName, allowEviction, isGranular, isSharded, isExternal, vaultPath, backupPrefix, blobPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenVault", reflect.TypeOf((*MockStorageRepository)(nil).OpenVault), vaultName, allowEviction, isGranular, isSharded, isExternal, vaultPath, backupPrefix, blobPath)
}

// ProtGetAsStream mocks base method.
func (m *MockStorageRepository) ProtGetAsStream(backupID, archiveFile string) (*os.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtGetAsStream", backupID, archiveFile)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProtGetAsStream indicates an expected call of ProtGetAsStream.
func (mr *MockStorageRepositoryMockRecorder) ProtGetAsStream(backupID, archiveFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtGetAsStream", reflect.TypeOf((*MockStorageRepository)(nil).ProtGetAsStream), backupID, archiveFile)
}
