// Code generated by MockGen. DO NOT EDIT.
// Source: backup-daemon.go

// Package rest is a generated GoMock package.
package rest

import (
	context "context"
	reflect "reflect"

	entity "github.com/Netcracker/qubership-backup-daemon-go/backup-daemon/app/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockBackupDaemonUseCase is a mock of BackupDaemonUseCase interface.
type MockBackupDaemonUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBackupDaemonUseCaseMockRecorder
}

// MockBackupDaemonUseCaseMockRecorder is the mock recorder for MockBackupDaemonUseCase.
type MockBackupDaemonUseCaseMockRecorder struct {
	mock *MockBackupDaemonUseCase
}

// NewMockBackupDaemonUseCase creates a new mock instance.
func NewMockBackupDaemonUseCase(ctrl *gomock.Controller) *MockBackupDaemonUseCase {
	mock := &MockBackupDaemonUseCase{ctrl: ctrl}
	mock.recorder = &MockBackupDaemonUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupDaemonUseCase) EXPECT() *MockBackupDaemonUseCaseMockRecorder {
	return m.recorder
}

// CreateS3PresignedURL mocks base method.
func (m *MockBackupDaemonUseCase) CreateS3PresignedURL(ctx context.Context, request entity.S3PresignedURLRequest) (entity.S3PresignedURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateS3PresignedURL", ctx, request)
	ret0, _ := ret[0].(entity.S3PresignedURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateS3PresignedURL indicates an expected call of CreateS3PresignedURL.
func (mr *MockBackupDaemonUseCaseMockRecorder) CreateS3PresignedURL(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateS3PresignedURL", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).CreateS3PresignedURL), ctx, request)
}

// EnqueueBackup mocks base method.
func (m *MockBackupDaemonUseCase) EnqueueBackup(ctx context.Context, request entity.BackupRequest) (entity.BackupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueBackup", ctx, request)
	ret0, _ := ret[0].(entity.BackupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnqueueBackup indicates an expected call of EnqueueBackup.
func (mr *MockBackupDaemonUseCaseMockRecorder) EnqueueBackup(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueBackup", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).EnqueueBackup), ctx, request)
}

// EnqueueEviction mocks base method.
func (m *MockBackupDaemonUseCase) EnqueueEviction(ctx context.Context, request entity.EvictRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueEviction", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueEviction indicates an expected call of EnqueueEviction.
func (mr *MockBackupDaemonUseCaseMockRecorder) EnqueueEviction(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueEviction", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).EnqueueEviction), ctx, request)
}

// GetJobStatus mocks base method.
func (m *MockBackupDaemonUseCase) GetJobStatus(ctx context.Context, request entity.JobStatusRequest) (entity.JobStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobStatus", ctx, request)
	ret0, _ := ret[0].(entity.JobStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobStatus indicates an expected call of GetJobStatus.
func (mr *MockBackupDaemonUseCaseMockRecorder) GetJobStatus(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobStatus", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).GetJobStatus), ctx, request)
}

// RemoveBackup mocks base method.
func (m *MockBackupDaemonUseCase) RemoveBackup(ctx context.Context, request entity.EvictByVaultRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBackup", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBackup indicates an expected call of RemoveBackup.
func (mr *MockBackupDaemonUseCaseMockRecorder) RemoveBackup(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBackup", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).RemoveBackup), ctx, request)
}

// RemoveBackupV2 mocks base method.
func (m *MockBackupDaemonUseCase) RemoveBackupV2(ctx context.Context, request entity.EvictByVaultV2Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBackupV2", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBackupV2 indicates an expected call of RemoveBackupV2.
func (mr *MockBackupDaemonUseCaseMockRecorder) RemoveBackupV2(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBackupV2", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).RemoveBackupV2), ctx, request)
}

// RestoreBackup mocks base method.
func (m *MockBackupDaemonUseCase) RestoreBackup(ctx context.Context, request entity.RestoreRequest) (entity.RestoreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreBackup", ctx, request)
	ret0, _ := ret[0].(entity.RestoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreBackup indicates an expected call of RestoreBackup.
func (mr *MockBackupDaemonUseCaseMockRecorder) RestoreBackup(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreBackup", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).RestoreBackup), ctx, request)
}
