// Code generated by MockGen. DO NOT EDIT.
// Source: backup-daemon.go
//
// Generated by this command:
//
//	mockgen -source=backup-daemon.go -destination=../rest/mock.go -package=rest
//

// Package rest is a generated GoMock package.
package rest

import (
	context "context"
	reflect "reflect"

	entity "github.com/Netcracker/qubership-backup-daemon-go/backup-daemon/app/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockBackupDaemonUseCase is a mock of BackupDaemonUseCase interface.
type MockBackupDaemonUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBackupDaemonUseCaseMockRecorder
}

// MockBackupDaemonUseCaseMockRecorder is the mock recorder for MockBackupDaemonUseCase.
type MockBackupDaemonUseCaseMockRecorder struct {
	mock *MockBackupDaemonUseCase
}

// NewMockBackupDaemonUseCase creates a new mock instance.
func NewMockBackupDaemonUseCase(ctrl *gomock.Controller) *MockBackupDaemonUseCase {
	mock := &MockBackupDaemonUseCase{ctrl: ctrl}
	mock.recorder = &MockBackupDaemonUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupDaemonUseCase) EXPECT() *MockBackupDaemonUseCaseMockRecorder {
	return m.recorder
}

// CreateS3PresignedURL mocks base method.
func (m *MockBackupDaemonUseCase) CreateS3PresignedURL(ctx context.Context, request entity.S3PresignedURLRequest) (entity.S3PresignedURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateS3PresignedURL", ctx, request)
	ret0, _ := ret[0].(entity.S3PresignedURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateS3PresignedURL indicates an expected call of CreateS3PresignedURL.
func (mr *MockBackupDaemonUseCaseMockRecorder) CreateS3PresignedURL(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateS3PresignedURL", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).CreateS3PresignedURL), ctx, request)
}

// EnqueueBackup mocks base method.
func (m *MockBackupDaemonUseCase) EnqueueBackup(ctx context.Context, request entity.BackupRequest) (entity.BackupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueBackup", ctx, request)
	ret0, _ := ret[0].(entity.BackupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnqueueBackup indicates an expected call of EnqueueBackup.
func (mr *MockBackupDaemonUseCaseMockRecorder) EnqueueBackup(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueBackup", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).EnqueueBackup), ctx, request)
}

// EnqueueEviction mocks base method.
func (m *MockBackupDaemonUseCase) EnqueueEviction(ctx context.Context, request entity.EvictRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueEviction", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueEviction indicates an expected call of EnqueueEviction.
func (mr *MockBackupDaemonUseCaseMockRecorder) EnqueueEviction(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueEviction", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).EnqueueEviction), ctx, request)
}

// GetBackupStats mocks base method.
func (m *MockBackupDaemonUseCase) GetBackupStats(ctx context.Context, vaultName, ts, backupPath, procType string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackupStats", ctx, vaultName, ts, backupPath, procType)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackupStats indicates an expected call of GetBackupStats.
func (mr *MockBackupDaemonUseCaseMockRecorder) GetBackupStats(ctx, vaultName, ts, backupPath, procType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackupStats", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).GetBackupStats), ctx, vaultName, ts, backupPath, procType)
}

// GetJobStatus mocks base method.
func (m *MockBackupDaemonUseCase) GetJobStatus(ctx context.Context, request entity.JobStatusRequest) (entity.JobStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobStatus", ctx, request)
	ret0, _ := ret[0].(entity.JobStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobStatus indicates an expected call of GetJobStatus.
func (mr *MockBackupDaemonUseCaseMockRecorder) GetJobStatus(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobStatus", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).GetJobStatus), ctx, request)
}

// ListBackup mocks base method.
func (m *MockBackupDaemonUseCase) ListBackup(ctx context.Context, procType, vaultPath string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackup", ctx, procType, vaultPath)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackup indicates an expected call of ListBackup.
func (mr *MockBackupDaemonUseCaseMockRecorder) ListBackup(ctx, procType, vaultPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackup", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).ListBackup), ctx, procType, vaultPath)
}

// ListBackups mocks base method.
func (m *MockBackupDaemonUseCase) ListBackups(ctx context.Context, procType string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackups", ctx, procType)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackups indicates an expected call of ListBackups.
func (mr *MockBackupDaemonUseCaseMockRecorder) ListBackups(ctx, procType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackups", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).ListBackups), ctx, procType)
}

// RemoveBackup mocks base method.
func (m *MockBackupDaemonUseCase) RemoveBackup(ctx context.Context, request entity.EvictByVaultRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBackup", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBackup indicates an expected call of RemoveBackup.
func (mr *MockBackupDaemonUseCaseMockRecorder) RemoveBackup(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBackup", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).RemoveBackup), ctx, request)
}

// RemoveBackupV2 mocks base method.
func (m *MockBackupDaemonUseCase) RemoveBackupV2(ctx context.Context, request entity.EvictByVaultV2Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBackupV2", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBackupV2 indicates an expected call of RemoveBackupV2.
func (mr *MockBackupDaemonUseCaseMockRecorder) RemoveBackupV2(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBackupV2", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).RemoveBackupV2), ctx, request)
}

// RemoveRestoreV2 mocks base method.
func (m *MockBackupDaemonUseCase) RemoveRestoreV2(ctx context.Context, request entity.EvictByVaultV2Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRestoreV2", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRestoreV2 indicates an expected call of RemoveRestoreV2.
func (mr *MockBackupDaemonUseCaseMockRecorder) RemoveRestoreV2(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRestoreV2", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).RemoveRestoreV2), ctx, request)
}

// RestoreBackup mocks base method.
func (m *MockBackupDaemonUseCase) RestoreBackup(ctx context.Context, request entity.RestoreRequest) (entity.RestoreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreBackup", ctx, request)
	ret0, _ := ret[0].(entity.RestoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreBackup indicates an expected call of RestoreBackup.
func (mr *MockBackupDaemonUseCaseMockRecorder) RestoreBackup(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreBackup", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).RestoreBackup), ctx, request)
}

// GetHealth mocks base method.
func (m *MockBackupDaemonUseCase) GetHealth(ctx context.Context, procType string) (entity.HealthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHealth", ctx, procType)
	ret0, _ := ret[0].(entity.HealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBackupDaemonUseCaseMockRecorder) GetHealth(ctx, procType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHealth", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).GetHealth), ctx, procType)
}

// Ready mocks base method.
func (m *MockBackupDaemonUseCase) Ready(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ready", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBackupDaemonUseCaseMockRecorder) Ready(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).Ready), ctx)
}

// Find mocks base method.
func (m *MockBackupDaemonUseCase) Find(ctx context.Context, request entity.FindRequest) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, request)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBackupDaemonUseCaseMockRecorder) Find(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).Find), ctx, request)
}

// UpdateEvictionPolicy mocks base method.
func (m *MockBackupDaemonUseCase) UpdateEvictionPolicy(ctx context.Context, request entity.EvictionPolicyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvictionPolicy", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBackupDaemonUseCaseMockRecorder) UpdateEvictionPolicy(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvictionPolicy", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).UpdateEvictionPolicy), ctx, request)
}

// TerminateBackup mocks base method.
func (m *MockBackupDaemonUseCase) TerminateBackup(ctx context.Context, request entity.TerminateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateBackup", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBackupDaemonUseCaseMockRecorder) TerminateBackup(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateBackup", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).TerminateBackup), ctx, request)
}

// GetQueueSize mocks base method.
func (m *MockBackupDaemonUseCase) GetQueueSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueSize")
	ret0, _ := ret[0].(int)
	return ret0
}

func (mr *MockBackupDaemonUseCaseMockRecorder) GetQueueSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueSize", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).GetQueueSize))
}

// DownloadBackup mocks base method.
func (m *MockBackupDaemonUseCase) DownloadBackup(ctx context.Context, backupID string) (string, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadBackup", ctx, backupID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockBackupDaemonUseCaseMockRecorder) DownloadBackup(ctx, backupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadBackup", reflect.TypeOf((*MockBackupDaemonUseCase)(nil).DownloadBackup), ctx, backupID)
}
