// Code generated by MockGen. DO NOT EDIT.
// Source: s3client.go
//
// Generated by this command:
//
//	mockgen -source=s3client.go -destination=s3mock.go -package=controller
//

// Package controller is a generated GoMock package.
package controller

import (
	context "context"
	io "io"
	reflect "reflect"

	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	manager "github.com/aws/aws-sdk-go-v2/feature/s3/manager"
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockS3ClientRepository is a mock of S3ClientRepository interface.
type MockS3ClientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockS3ClientRepositoryMockRecorder
	isgomock struct{}
}

// MockS3ClientRepositoryMockRecorder is the mock recorder for MockS3ClientRepository.
type MockS3ClientRepositoryMockRecorder struct {
	mock *MockS3ClientRepository
}

// NewMockS3ClientRepository creates a new mock instance.
func NewMockS3ClientRepository(ctrl *gomock.Controller) *MockS3ClientRepository {
	mock := &MockS3ClientRepository{ctrl: ctrl}
	mock.recorder = &MockS3ClientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3ClientRepository) EXPECT() *MockS3ClientRepositoryMockRecorder {
	return m.recorder
}

// CreatePresignedUrl mocks base method.
func (m *MockS3ClientRepository) CreatePresignedUrl(ctx context.Context, objectName string, expiration int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePresignedUrl", ctx, objectName, expiration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePresignedUrl indicates an expected call of CreatePresignedUrl.
func (mr *MockS3ClientRepositoryMockRecorder) CreatePresignedUrl(ctx, objectName, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePresignedUrl", reflect.TypeOf((*MockS3ClientRepository)(nil).CreatePresignedUrl), ctx, objectName, expiration)
}

// DeletePrefix mocks base method.
func (m *MockS3ClientRepository) DeletePrefix(ctx context.Context, prefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrefix", ctx, prefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrefix indicates an expected call of DeletePrefix.
func (mr *MockS3ClientRepositoryMockRecorder) DeletePrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrefix", reflect.TypeOf((*MockS3ClientRepository)(nil).DeletePrefix), ctx, prefix)
}

// DownloadFolder mocks base method.
func (m *MockS3ClientRepository) DownloadFolder(ctx context.Context, s3Folder, localDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFolder", ctx, s3Folder, localDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadFolder indicates an expected call of DownloadFolder.
func (mr *MockS3ClientRepositoryMockRecorder) DownloadFolder(ctx, s3Folder, localDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFolder", reflect.TypeOf((*MockS3ClientRepository)(nil).DownloadFolder), ctx, s3Folder, localDir)
}

// ListFiles mocks base method.
func (m *MockS3ClientRepository) ListFiles(ctx context.Context, path string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", ctx, path)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockS3ClientRepositoryMockRecorder) ListFiles(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockS3ClientRepository)(nil).ListFiles), ctx, path)
}

// UploadFolder mocks base method.
func (m *MockS3ClientRepository) UploadFolder(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFolder", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFolder indicates an expected call of UploadFolder.
func (mr *MockS3ClientRepositoryMockRecorder) UploadFolder(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFolder", reflect.TypeOf((*MockS3ClientRepository)(nil).UploadFolder), ctx, path)
}

// UploadFolderWithPrefix mocks base method.
func (m *MockS3ClientRepository) UploadFolderWithPrefix(ctx context.Context, path, prefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFolderWithPrefix", ctx, path, prefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFolderWithPrefix indicates an expected call of UploadFolderWithPrefix.
func (mr *MockS3ClientRepositoryMockRecorder) UploadFolderWithPrefix(ctx, path, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFolderWithPrefix", reflect.TypeOf((*MockS3ClientRepository)(nil).UploadFolderWithPrefix), ctx, path, prefix)
}

// MockPresignClientInterface is a mock of PresignClientInterface interface.
type MockPresignClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPresignClientInterfaceMockRecorder
	isgomock struct{}
}

// MockPresignClientInterfaceMockRecorder is the mock recorder for MockPresignClientInterface.
type MockPresignClientInterfaceMockRecorder struct {
	mock *MockPresignClientInterface
}

// NewMockPresignClientInterface creates a new mock instance.
func NewMockPresignClientInterface(ctrl *gomock.Controller) *MockPresignClientInterface {
	mock := &MockPresignClientInterface{ctrl: ctrl}
	mock.recorder = &MockPresignClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresignClientInterface) EXPECT() *MockPresignClientInterfaceMockRecorder {
	return m.recorder
}

// PresignGetObject mocks base method.
func (m *MockPresignClientInterface) PresignGetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PresignGetObject", varargs...)
	ret0, _ := ret[0].(*v4.PresignedHTTPRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignGetObject indicates an expected call of PresignGetObject.
func (mr *MockPresignClientInterfaceMockRecorder) PresignGetObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGetObject", reflect.TypeOf((*MockPresignClientInterface)(nil).PresignGetObject), varargs...)
}

// MockDownloaderInterface is a mock of DownloaderInterface interface.
type MockDownloaderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDownloaderInterfaceMockRecorder
	isgomock struct{}
}

// MockDownloaderInterfaceMockRecorder is the mock recorder for MockDownloaderInterface.
type MockDownloaderInterfaceMockRecorder struct {
	mock *MockDownloaderInterface
}

// NewMockDownloaderInterface creates a new mock instance.
func NewMockDownloaderInterface(ctrl *gomock.Controller) *MockDownloaderInterface {
	mock := &MockDownloaderInterface{ctrl: ctrl}
	mock.recorder = &MockDownloaderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloaderInterface) EXPECT() *MockDownloaderInterfaceMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockDownloaderInterface) Download(ctx context.Context, w io.WriterAt, input *s3.GetObjectInput, options ...func(*manager.Downloader)) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, w, input}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Download", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockDownloaderInterfaceMockRecorder) Download(ctx, w, input any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, w, input}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockDownloaderInterface)(nil).Download), varargs...)
}

// MockUploaderInterface is a mock of UploaderInterface interface.
type MockUploaderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUploaderInterfaceMockRecorder
	isgomock struct{}
}

// MockUploaderInterfaceMockRecorder is the mock recorder for MockUploaderInterface.
type MockUploaderInterfaceMockRecorder struct {
	mock *MockUploaderInterface
}

// NewMockUploaderInterface creates a new mock instance.
func NewMockUploaderInterface(ctrl *gomock.Controller) *MockUploaderInterface {
	mock := &MockUploaderInterface{ctrl: ctrl}
	mock.recorder = &MockUploaderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploaderInterface) EXPECT() *MockUploaderInterfaceMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockUploaderInterface) Upload(ctx context.Context, input *s3.PutObjectInput, opts ...func(*manager.Uploader)) (*manager.UploadOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upload", varargs...)
	ret0, _ := ret[0].(*manager.UploadOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockUploaderInterfaceMockRecorder) Upload(ctx, input any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockUploaderInterface)(nil).Upload), varargs...)
}

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// AbortMultipartUpload mocks base method.
func (m *MockClientInterface) AbortMultipartUpload(arg0 context.Context, arg1 *s3.AbortMultipartUploadInput, arg2 ...func(*s3.Options)) (*s3.AbortMultipartUploadOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AbortMultipartUpload", varargs...)
	ret0, _ := ret[0].(*s3.AbortMultipartUploadOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockClientInterfaceMockRecorder) AbortMultipartUpload(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMultipartUpload", reflect.TypeOf((*MockClientInterface)(nil).AbortMultipartUpload), varargs...)
}

// CompleteMultipartUpload mocks base method.
func (m *MockClientInterface) CompleteMultipartUpload(arg0 context.Context, arg1 *s3.CompleteMultipartUploadInput, arg2 ...func(*s3.Options)) (*s3.CompleteMultipartUploadOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CompleteMultipartUpload", varargs...)
	ret0, _ := ret[0].(*s3.CompleteMultipartUploadOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockClientInterfaceMockRecorder) CompleteMultipartUpload(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultipartUpload", reflect.TypeOf((*MockClientInterface)(nil).CompleteMultipartUpload), varargs...)
}

// CreateMultipartUpload mocks base method.
func (m *MockClientInterface) CreateMultipartUpload(arg0 context.Context, arg1 *s3.CreateMultipartUploadInput, arg2 ...func(*s3.Options)) (*s3.CreateMultipartUploadOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateMultipartUpload", varargs...)
	ret0, _ := ret[0].(*s3.CreateMultipartUploadOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockClientInterfaceMockRecorder) CreateMultipartUpload(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultipartUpload", reflect.TypeOf((*MockClientInterface)(nil).CreateMultipartUpload), varargs...)
}

// DeleteObjects mocks base method.
func (m *MockClientInterface) DeleteObjects(arg0 context.Context, arg1 *s3.DeleteObjectsInput, arg2 ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteObjects", varargs...)
	ret0, _ := ret[0].(*s3.DeleteObjectsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockClientInterfaceMockRecorder) DeleteObjects(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjects", reflect.TypeOf((*MockClientInterface)(nil).DeleteObjects), varargs...)
}

// GetObject mocks base method.
func (m *MockClientInterface) GetObject(arg0 context.Context, arg1 *s3.GetObjectInput, arg2 ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(*s3.GetObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockClientInterfaceMockRecorder) GetObject(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockClientInterface)(nil).GetObject), varargs...)
}

// HeadObject mocks base method.
func (m *MockClientInterface) HeadObject(arg0 context.Context, arg1 *s3.HeadObjectInput, arg2 ...func(*s3.Options)) (*s3.HeadObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HeadObject", varargs...)
	ret0, _ := ret[0].(*s3.HeadObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockClientInterfaceMockRecorder) HeadObject(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObject", reflect.TypeOf((*MockClientInterface)(nil).HeadObject), varargs...)
}

// ListObjectsV2 mocks base method.
func (m *MockClientInterface) ListObjectsV2(ctx context.Context, params *s3.ListObjectsV2Input, optFns ...func(*s3.Options)) (*s3.ListObjectsV2Output, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListObjectsV2", varargs...)
	ret0, _ := ret[0].(*s3.ListObjectsV2Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsV2 indicates an expected call of ListObjectsV2.
func (mr *MockClientInterfaceMockRecorder) ListObjectsV2(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsV2", reflect.TypeOf((*MockClientInterface)(nil).ListObjectsV2), varargs...)
}

// PutObject mocks base method.
func (m *MockClientInterface) PutObject(arg0 context.Context, arg1 *s3.PutObjectInput, arg2 ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObject", varargs...)
	ret0, _ := ret[0].(*s3.PutObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockClientInterfaceMockRecorder) PutObject(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockClientInterface)(nil).PutObject), varargs...)
}

// UploadPart mocks base method.
func (m *MockClientInterface) UploadPart(arg0 context.Context, arg1 *s3.UploadPartInput, arg2 ...func(*s3.Options)) (*s3.UploadPartOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadPart", varargs...)
	ret0, _ := ret[0].(*s3.UploadPartOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPart indicates an expected call of UploadPart.
func (mr *MockClientInterfaceMockRecorder) UploadPart(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPart", reflect.TypeOf((*MockClientInterface)(nil).UploadPart), varargs...)
}
