// Code generated by MockGen. DO NOT EDIT.
// Source: executor.go
//
// Generated by this command:
//
//	mockgen -source=executor.go -destination=../tasks/executor-mock.go -package=tasks
//

// Package tasks is a generated GoMock package.
package tasks

import (
	context "context"
	reflect "reflect"

	entity "github.com/Netcracker/qubership-backup-daemon-go/backup-daemon/app/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandExecutor is a mock of CommandExecutor interface.
type MockCommandExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockCommandExecutorMockRecorder
	isgomock struct{}
}

// MockCommandExecutorMockRecorder is the mock recorder for MockCommandExecutor.
type MockCommandExecutorMockRecorder struct {
	mock *MockCommandExecutor
}

// NewMockCommandExecutor creates a new mock instance.
func NewMockCommandExecutor(ctrl *gomock.Controller) *MockCommandExecutor {
	mock := &MockCommandExecutor{ctrl: ctrl}
	mock.recorder = &MockCommandExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandExecutor) EXPECT() *MockCommandExecutorMockRecorder {
	return m.recorder
}

// ExecuteEvictCmd mocks base method.
func (m *MockCommandExecutor) ExecuteEvictCmd(vaultFolder string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteEvictCmd", vaultFolder)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteEvictCmd indicates an expected call of ExecuteEvictCmd.
func (mr *MockCommandExecutorMockRecorder) ExecuteEvictCmd(vaultFolder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteEvictCmd", reflect.TypeOf((*MockCommandExecutor)(nil).ExecuteEvictCmd), vaultFolder)
}

// GetBackupDBs mocks base method.
func (m *MockCommandExecutor) GetBackupDBs(vaultFolder string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackupDBs", vaultFolder)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackupDBs indicates an expected call of GetBackupDBs.
func (mr *MockCommandExecutorMockRecorder) GetBackupDBs(vaultFolder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackupDBs", reflect.TypeOf((*MockCommandExecutor)(nil).GetBackupDBs), vaultFolder)
}

// PerformBackup mocks base method.
func (m *MockCommandExecutor) PerformBackup(vault entity.Vault, dbs []entity.DBEntry, customVars map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformBackup", vault, dbs, customVars)
	ret0, _ := ret[0].(error)
	return ret0
}

// PerformBackup indicates an expected call of PerformBackup.
func (mr *MockCommandExecutorMockRecorder) PerformBackup(vault, dbs, customVars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformBackup", reflect.TypeOf((*MockCommandExecutor)(nil).PerformBackup), vault, dbs, customVars)
}

// PerformEviction mocks base method.
func (m *MockCommandExecutor) PerformEviction(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformEviction", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PerformEviction indicates an expected call of PerformEviction.
func (mr *MockCommandExecutorMockRecorder) PerformEviction(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformEviction", reflect.TypeOf((*MockCommandExecutor)(nil).PerformEviction), ctx)
}

// PerformRestore mocks base method.
func (m *MockCommandExecutor) PerformRestore(vaultFolder string, dbs []entity.DBEntry, dbmap, customVariables map[string]string, external bool, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformRestore", vaultFolder, dbs, dbmap, customVariables, external, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PerformRestore indicates an expected call of PerformRestore.
func (mr *MockCommandExecutorMockRecorder) PerformRestore(vaultFolder, dbs, dbmap, customVariables, external, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformRestore", reflect.TypeOf((*MockCommandExecutor)(nil).PerformRestore), vaultFolder, dbs, dbmap, customVariables, external, taskID)
}

// SetEvictionPolicy mocks base method.
func (m *MockCommandExecutor) SetEvictionPolicy(full, granular string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEvictionPolicy", full, granular)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEvictionPolicy indicates an expected call of SetEvictionPolicy.
func (mr *MockCommandExecutorMockRecorder) SetEvictionPolicy(full, granular any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEvictionPolicy", reflect.TypeOf((*MockCommandExecutor)(nil).SetEvictionPolicy), full, granular)
}

// ExecuteMarkerSetCmd mocks base method.
func (m *MockCommandExecutor) ExecuteMarkerSetCmd(marker string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteMarkerSetCmd", marker)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteMarkerSetCmd indicates an expected call of ExecuteMarkerSetCmd.
func (mr *MockCommandExecutorMockRecorder) ExecuteMarkerSetCmd(marker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteMarkerSetCmd", reflect.TypeOf((*MockCommandExecutor)(nil).ExecuteMarkerSetCmd), marker)
}

// ExecuteMarkerValidateCmd mocks base method.
func (m *MockCommandExecutor) ExecuteMarkerValidateCmd(marker string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteMarkerValidateCmd", marker)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteMarkerValidateCmd indicates an expected call of ExecuteMarkerValidateCmd.
func (mr *MockCommandExecutorMockRecorder) ExecuteMarkerValidateCmd(marker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteMarkerValidateCmd", reflect.TypeOf((*MockCommandExecutor)(nil).ExecuteMarkerValidateCmd), marker)
}
